"""empty message

Revision ID: 8251c700730b
Revises: 7f645a00f9d7
Create Date: 2020-10-18 20:29:45.785103

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8251c700730b'
down_revision = '7f645a00f9d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('show', sa.Column('artist_name', sa.String(), nullable=True))
    op.add_column('show', sa.Column('venue_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('show', 'venue_name')
    op.drop_column('show', 'artist_name')
    # ### end Alembic commands ###
